services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '4000:4000'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
